name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.cache/ms-playwright

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22]

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-and-cache
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck

      - name: Install Playwright Dependencies
        run: pnpm exec playwright install chromium firefox --with-deps --only-shell

      - name: Test
        run: pnpm test

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: vitest-screenshots-${{ matrix.node-version }}
          path: test/__screenshots__
          retention-days: 30

  publish-preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - uses: ./.github/actions/setup-and-cache
        with:
          node-version: 22

      - name: Install & Build & Publish
        run: |
          pnpm install
          pnpm build
          npx pkg-pr-new publish --compact
